# Development-specific Docker Compose configuration

services:
  # Override web service for development
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-not-for-production
      - DB_NAME=hris_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - LOAD_INITIAL_DATA=true
    volumes:
      - .:/app  # Mount source code for hot reload
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  # Override celery for development
  celery:
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-not-for-production
      - DB_NAME=hris_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app  # Mount source code
      - ./logs:/app/logs
      - ./media:/app/media

  # Override celery-beat for development
  celery-beat:
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-not-for-production
      - DB_NAME=hris_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app  # Mount source code
      - ./logs:/app/logs

  # pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hris_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hris.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    profiles:
      - dev-tools

  # Redis Commander for Redis management (development only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: hris_redis_commander
    environment:
      REDIS_HOSTS: "local:redis:6379"
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - dev-tools

volumes:
  pgadmin_data: