# Generated by Django 4.2.7 on 2025-07-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_azure_ad_fields'),
    ]

    operations = [
    ]
