# Generated by Django 4.2.7 on 2025-07-18 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_manual_jobtitle_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title_old',
            field=models.CharField(blank=True, help_text='Temporary field for migration', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Job description and responsibilities')),
                ('level', models.CharField(blank=True, help_text='Job level (e.g., Entry, Mid, Senior, Lead, Manager)', max_length=50)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary range for this position', max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary range for this position', max_digits=10, null=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated list of required skills')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Primary department for this job title', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='employees.department')),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'Job Titles',
                'db_table': 'job_titles',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='job_title',
            field=models.ForeignKey(blank=True, help_text='Employee job title/position', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle'),
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['title'], name='job_titles_title_1bce60_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['department', 'is_active'], name='job_titles_departm_feb834_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['level'], name='job_titles_level_de00d1_idx'),
        ),
    ]
