# Generated by Django 4.2.7 on 2025-07-07 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerAppsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name for identification', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this PowerApps integration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], default='inactive', help_text='Current status of this configuration', max_length=20)),
                ('api_key', models.CharField(help_text='Unique API key for PowerApps authentication', max_length=255, unique=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list, help_text='Allowed origins for CORS (PowerApps URLs)')),
                ('field_mapping', models.JSONField(default=dict, help_text='JSON mapping of PowerApps form fields to DANI applicant fields')),
                ('required_fields', models.JSONField(default=list, help_text='List of required PowerApps form fields')),
                ('resume_field_name', models.CharField(default='resume_file', help_text='PowerApps field name for resume upload', max_length=100)),
                ('cover_letter_field_name', models.CharField(blank=True, default='cover_letter_file', help_text='PowerApps field name for cover letter upload', max_length=100)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum file size in MB for uploaded files')),
                ('allowed_file_types', models.JSONField(default=list, help_text="Allowed file extensions (e.g., ['pdf', 'doc', 'docx'])")),
                ('default_application_source', models.CharField(default='PowerApps Form', help_text='Default source to assign to applications from this form', max_length=50)),
                ('allowed_email_domains', models.JSONField(blank=True, default=list, help_text='Restrict applications to specific email domains')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Require email verification before processing application')),
                ('enable_duplicate_detection', models.BooleanField(default=True, help_text='Prevent duplicate applications based on email and job')),
                ('auto_send_confirmation', models.BooleanField(default=True, help_text='Automatically send confirmation email to applicants')),
                ('confirmation_email_template', models.TextField(blank=True, help_text='Custom email template for application confirmations')),
                ('notification_emails', models.JSONField(blank=True, default=list, help_text='Email addresses to notify when new applications arrive')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=100, help_text='Maximum applications per hour from this configuration')),
                ('custom_validation_rules', models.JSONField(blank=True, default=dict, help_text='Custom validation rules for form data')),
                ('webhook_url', models.URLField(blank=True, help_text='Optional webhook URL to call after successful application submission')),
                ('total_submissions', models.PositiveIntegerField(default=0, help_text='Total number of applications received through this configuration')),
                ('successful_submissions', models.PositiveIntegerField(default=0, help_text='Number of successfully processed applications')),
                ('last_submission_date', models.DateTimeField(blank=True, help_text='Date and time of last application submission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_assign_to_job', models.ForeignKey(blank=True, help_text='Automatically assign applications to this job posting', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.jobposting')),
                ('created_by', models.ForeignKey(help_text='User who created this configuration', on_delete=django.db.models.deletion.PROTECT, related_name='created_powerapps_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PowerApps Configuration',
                'verbose_name_plural': 'PowerApps Configurations',
                'db_table': 'powerapps_configurations',
                'indexes': [models.Index(fields=['status'], name='powerapps_c_status_325481_idx'), models.Index(fields=['api_key'], name='powerapps_c_api_key_390a2d_idx'), models.Index(fields=['auto_assign_to_job'], name='powerapps_c_auto_as_4bc1f4_idx')],
            },
        ),
    ]
