# Generated by Django 4.2.7 on 2025-07-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_azure_ad_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_azure_a_45f756_idx',
            old_name='users_azure_ad_object_id_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_azure_a_4997d2_idx',
            old_name='users_azure_ad_sync_status_idx',
        ),
    ]
