# Generated by Django 4.2.7 on 2025-07-05 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_azure_ad_fields'),
        ('accounts', '0004_add_azure_ad_sync_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or organization name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('intern', 'Intern'), ('temporary', 'Temporary')], help_text='Employment type', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Employee hire date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Direct manager or supervisor', limit_choices_to={'role__in': ['admin', 'hr_manager', 'hiring_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='office_location',
            field=models.CharField(blank=True, help_text='Primary office or work location', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='employees.department'),
        ),
    ]
