# Generated by Django 4.2.7 on 2025-07-05 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_company_name_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business email address (populates Azure AD email property)', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Username/UPN for login and Azure AD User Principal Name', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
