# Generated by Django 4.2.7 on 2025-07-05 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_business_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether this user can be assigned as a manager to other users'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Direct manager or supervisor', limit_choices_to={'is_active': True, 'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_direct_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
