# Generated by Django 4.2.7 on 2025-07-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_is_manager_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='azureadsettings',
            name='enable_automatic_sync',
            field=models.BooleanField(default=False, help_text='Enable automatic periodic synchronization of all users'),
        ),
        migrations.AddField(
            model_name='azureadsettings',
            name='last_automatic_sync',
            field=models.DateTimeField(blank=True, help_text='Last time automatic sync was performed', null=True),
        ),
        migrations.AddField(
            model_name='azureadsettings',
            name='sync_interval_hours',
            field=models.PositiveIntegerField(default=24, help_text='Interval in hours between automatic sync operations'),
        ),
    ]
